/*
 * Ory Kratos API
 *
 * Documentation for all public and administrative Ory Kratos APIs. Public and administrative APIs are exposed on different ports. Public APIs can face the public internet without any protection while administrative APIs should never be exposed without prior authorization. To protect the administative API port you should use something like Nginx, Ory Oathkeeper, or any other technology capable of authorizing incoming requests.
 *
 * API version: 1.0.0
 * Contact: hi@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SubmitSelfServiceVerificationFlowWithCodeMethodBody struct for SubmitSelfServiceVerificationFlowWithCodeMethodBody
type SubmitSelfServiceVerificationFlowWithCodeMethodBody struct {
	// Code from verification email  Sent to the user once a verification has been initiated and is used to prove that the user is in possession of the email
	Code *string `json:"code,omitempty"`
	// Sending the anti-csrf token is only required for browser login flows.
	CsrfToken *string `json:"csrf_token,omitempty"`
	// Email to Verify  Needs to be set when initiating the flow. If the email is a registered verification email, a verification code will be sent. If the email is not known, an email with details on what happened will be sent instead.  format: email
	Email string `json:"email"`
	// Method supports `link` and `code` only right now.
	Method string `json:"method"`
}

// NewSubmitSelfServiceVerificationFlowWithCodeMethodBody instantiates a new SubmitSelfServiceVerificationFlowWithCodeMethodBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSelfServiceVerificationFlowWithCodeMethodBody(email string, method string) *SubmitSelfServiceVerificationFlowWithCodeMethodBody {
	this := SubmitSelfServiceVerificationFlowWithCodeMethodBody{}
	this.Email = email
	this.Method = method
	return &this
}

// NewSubmitSelfServiceVerificationFlowWithCodeMethodBodyWithDefaults instantiates a new SubmitSelfServiceVerificationFlowWithCodeMethodBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSelfServiceVerificationFlowWithCodeMethodBodyWithDefaults() *SubmitSelfServiceVerificationFlowWithCodeMethodBody {
	this := SubmitSelfServiceVerificationFlowWithCodeMethodBody{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) SetCode(v string) {
	o.Code = &v
}

// GetCsrfToken returns the CsrfToken field value if set, zero value otherwise.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetCsrfToken() string {
	if o == nil || o.CsrfToken == nil {
		var ret string
		return ret
	}
	return *o.CsrfToken
}

// GetCsrfTokenOk returns a tuple with the CsrfToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetCsrfTokenOk() (*string, bool) {
	if o == nil || o.CsrfToken == nil {
		return nil, false
	}
	return o.CsrfToken, true
}

// HasCsrfToken returns a boolean if a field has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) HasCsrfToken() bool {
	if o != nil && o.CsrfToken != nil {
		return true
	}

	return false
}

// SetCsrfToken gets a reference to the given string and assigns it to the CsrfToken field.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) SetCsrfToken(v string) {
	o.CsrfToken = &v
}

// GetEmail returns the Email field value
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) SetEmail(v string) {
	o.Email = v
}

// GetMethod returns the Method field value
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *SubmitSelfServiceVerificationFlowWithCodeMethodBody) SetMethod(v string) {
	o.Method = v
}

func (o SubmitSelfServiceVerificationFlowWithCodeMethodBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.CsrfToken != nil {
		toSerialize["csrf_token"] = o.CsrfToken
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["method"] = o.Method
	}
	return json.Marshal(toSerialize)
}

type NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody struct {
	value *SubmitSelfServiceVerificationFlowWithCodeMethodBody
	isSet bool
}

func (v NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) Get() *SubmitSelfServiceVerificationFlowWithCodeMethodBody {
	return v.value
}

func (v *NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) Set(val *SubmitSelfServiceVerificationFlowWithCodeMethodBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSelfServiceVerificationFlowWithCodeMethodBody(val *SubmitSelfServiceVerificationFlowWithCodeMethodBody) *NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody {
	return &NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody{value: val, isSet: true}
}

func (v NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSelfServiceVerificationFlowWithCodeMethodBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
